### ISSUE TITLE
Content-length header is missing when authorize

### ISSUE THREAD

**Issue by mtellezj** [chiply/spot4e#12]
When I run `spot4e-authorize` and paste my auth code I get an "**json-read-table-error**" message. Looking at the end of `json-read-from-string` I found "**POST requests require a Content-length header. That’s all we know.**", so I check `spot4e-authorize ()` function and there is no Content-Length header. I add the following to that function:

    ("Content-Length" . "0")

and now auth works, but when I try to `spot4e-refresh ()` I get the same error. Again, adding `("Content-Length" . "0")` make things work. I can make a PR with this, my only question is: the `"0"` is the best value for `Content-Length`?

**Comment by chiply** [comment]
Hi, just merged your pull request - thanks!  I'm not sure if 0 is the right length, but I've read similar things online.  I'll change it in the future if I find a more logical value.  But for now it works.
