### ISSUE TITLE
helm-M-x: End of file while parsing JSON

### ISSUE THREAD

**Issue by aldoridhoni** [chiply/spot4e#15]
When I call command `spot4e-message-currently-playing` when I don't have any Spotify app open and connected, the API returns `HTTP/1.1 204 No Content` with no JSON content.

`json-read-from-string` function inside `spot4e-retrieve-url-to-alist-synchronously` does not handle the case.

But after I open Spotify App and play a track, it works OK.

**Comment by chiply** [comment]
Hi @aldoridhoni, nothing out of the ordinary there.  As mentioned in the readme, spot4e is not designed to integrate directly with Spotify on your machine.  Rather, it interacts with the spotify API to control play back on devices.  As such, and as you pointed out, Spotify needs to be open somewhere (could be your computer, your phone, your alexa or google home etc).  That being said, the error you see isn't very helpful!  I will fix that, closing this issue for now.
