### ISSUE TITLE
Invalid variables

### ISSUE THREAD

**Issue by sebastiencs** [chiply/spot4e#2]
After pulling the last changes, It seems that the variables `spot4e-refresh-token`, `spot4e-access-token` and some others no longer exist.
It makes `spot4e` throws error and I can't use it

**Comment by sebastiencs** [comment]
My bad, `spot4e` stills works but the variables should be declared

**Comment by chiply** [comment]
Hi sebastien, thanks for pointing this out.

Could you tell me what is meant by the variables must be declared?  Hoping I can push a fix if need be.
