### ISSUE TITLE
Create a separate package for the webapi

### ISSUE THREAD

**Issue by Fuco1** [chiply/spot4e#8]
Hey.  This seems like the most complete project so far focused on using the new WebAPI from spotify.

I would like it very much if there existed a package just implementing the api, similarly to https://github.com/sigma/gh.el for github.  It has no UI, just provides elisp bindings for the API.

People can then build their own clients around whatever structure/layout they choose instead of being limited to say helm as this package is currently.

My question is, would you want to collaborate on something like that, does it make sense?

**Comment by chiply** [comment]
Sounds like a cool idea!  This package is a little opinionated as it assumes the user likes helm.  

A separate package that provides elisp bindings for the Spotify API sounds like a wonderful idea.

I'm happy to collaborate!  Let me put together a first draft over the next few days and we can get cracking.  I'll probably have this ready by Sunday, unless you want to take a stab at it!  Might be worth re-writing form scratch as this is my first elisp project and the code is likely a little convoluted.

**Comment by Fuco1** [comment]
I would quite liberally borrow the basic architecture from gh.el, sigma is a wonderful developer and the thing is quite thought-out.

**Comment by chiply** [comment]
Awesome - I'm on board :-).  Feel free to reach out to me, I just sent you an email.  I'm going to leave this issue open as an enhancement for a little while as so other people may see it.

**Comment by chiply** [comment]
Hi Fuco1 - going to close this issue as this is a separate concern from spot4e.  Was willing to help, but unfortunately don't have the bandwidth anymore!

**Comment by Fuco1** [comment]
Me neither, no problem! :)
